package com.cogmento.automation.web.page;

import com.cogmento.automation.web.page.UserPageTemplate;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.NoSuchElementException;


/**
* @author  Code generated by ATFG (Automation Test Framework Generator) created by Harini Kumar <harini.kumar.email@gmail.com> & Shashikanth Rao <shashikanth.h.rao@gmail.com>
* @version 1.0
* @since   2021-09-20 
*/

public class CompanyViewPage extends UserPageTemplate {
	
		public CompanyViewPage(WebDriver driver) {
		super(driver);
	}

}