package com.cogmento.automation.web.page;

import com.cogmento.automation.web.page.GenericPage;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.NoSuchElementException;


/**
* @author  Code generated by ATFG (Automation Test Framework Generator) created by Harini Kumar <harini.kumar.email@gmail.com> & Shashikanth Rao <shashikanth.h.rao@gmail.com>
* @version 1.0
* @since   2021-09-20 
*/

public class LoginPage extends GenericPage {
	
		//ElementType:txt  Description:Text box or text area
	private By usernameLocator = By.xpath("//input[@name='email']");

	//ElementType:txt  Description:Text box or text area
	private By passwordLocator = By.xpath("//input[@name='password']");

	//ElementType:def  Description:Default Element. Link, button etc.. That are clickable
	private By loginLocator = By.xpath("//div[@class='ui fluid large blue submit button']");

	public LoginPage(WebDriver driver) {
		super(driver);
	}
	//username methods
	
	public By getUsernameLocator() {
		return usernameLocator;
	}
	
	public WebElement getUsername() {
		return getDriver().findElement(usernameLocator);
	}

	public void goToUsername() {	    
		Actions actions = new Actions(getDriver());
		actions.moveToElement(getUsername()).build().perform();						
	}
	
	public void clickUsername() {
		getUsername().click();
		//Alternative 1:  new Actions(getDriver()).moveToElement(getUsername()).click().build().perform();
		//Alternative 2:  ((JavascriptExecutor)getDriver()).executeScript("arguments[0].click()", getUsername());						
	}
		
	public void clearTextUsername() {
		getUsername().clear();						
	}
	
	public void setTextUsername(String text) {
		clickUsername();
		getUsername().clear();
		getUsername().sendKeys(text);
	}

	public String getTextUsername() {
		return getUsername().getText();
	}
		//password methods
	
	public By getPasswordLocator() {
		return passwordLocator;
	}
	
	public WebElement getPassword() {
		return getDriver().findElement(passwordLocator);
	}

	public void goToPassword() {	    
		Actions actions = new Actions(getDriver());
		actions.moveToElement(getPassword()).build().perform();						
	}
	
	public void clickPassword() {
		getPassword().click();
		//Alternative 1:  new Actions(getDriver()).moveToElement(getPassword()).click().build().perform();
		//Alternative 2:  ((JavascriptExecutor)getDriver()).executeScript("arguments[0].click()", getPassword());						
	}
		
	public void clearTextPassword() {
		getPassword().clear();						
	}
	
	public void setTextPassword(String text) {
		clickPassword();
		getPassword().clear();
		getPassword().sendKeys(text);
	}

	public String getTextPassword() {
		return getPassword().getText();
	}
		//login methods
	 
	public By getLoginLocator() {
		return loginLocator;
	}
	
	public WebElement getLogin() {
		return getDriver().findElement(loginLocator);		
	}

	public void goToLogin() {
		Actions actions = new Actions(getDriver());
		actions.moveToElement(getLogin()).build().perform();					
	}
	
	public void clickLogin() {
		getLogin().click();
		//Alternative 1:  new Actions(getDriver()).moveToElement(getLogin()).click().build().perform();
		//Alternative 2:  ((JavascriptExecutor)getDriver()).executeScript("arguments[0].click()", getLogin());								
	}

}